// <auto-generated />
using System;
using AgroFlow.Data.Appointments;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroFlow.Data.Migrations.Appointments
{
    [DbContext(typeof(AgroFlowDbContext))]
    partial class AgroFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("AgroFlow.Domain.Entities.Camion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FleetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngenioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedPlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngenioId", "NormalizedPlate")
                        .IsUnique();

                    b.ToTable("Camiones", (string)null);
                });

            modelBuilder.Entity("AgroFlow.Domain.Entities.Finca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngenioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngenioId", "NormalizedCode")
                        .IsUnique();

                    b.ToTable("Fincas", (string)null);
                });

            modelBuilder.Entity("AgroFlow.Domain.Entities.Ingenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingenios", (string)null);
                });

            modelBuilder.Entity("AgroFlow.Domain.Entities.Transportista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngenioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedDni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedWhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngenioId", "NormalizedWhatsApp")
                        .IsUnique();

                    b.ToTable("Transportistas", (string)null);
                });

            modelBuilder.Entity("AgroFlow.Domain.Entities.TransportistaCamion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CamionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngenioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransportistaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CamionId")
                        .IsUnique()
                        .HasFilter("IsActive = 1");

                    b.HasIndex("TransportistaId", "CamionId")
                        .IsUnique();

                    b.ToTable("TransportistaCamiones", (string)null);
                });

            modelBuilder.Entity("AgroFlow.Domain.Entities.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CamionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CutAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedLoadTons")
                        .HasColumnType("REAL");

                    b.Property<Guid>("FincaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngenioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransportistaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VentanaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CamionId")
                        .IsUnique()
                        .HasFilter("IsActive = 1");

                    b.HasIndex("IngenioId", "VentanaId");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("AgroFlow.Domain.Entities.Ventana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngenioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Occupied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngenioId", "StartAt");

                    b.ToTable("Ventanas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ventanas_Occupied_Range", "Occupied >= 0 AND Occupied <= Capacity");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
